### ISSUE TITLE
DT40 PrinterManger java.lang.RuntimeException: stub

### ISSUE THREAD

**Issue by xiaoqiaotq** [urovosamples/SDK_ReleaseforAndroid#14]
05/27 21:45:14: Launching 'PrinterManager' on Urovo DT40.
$ adb shell am start -n "com.example.printersample/com.example.printersample.PrinterManagerActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 8186 on device 'urovo-dt40-4923be62'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/Adreno: QUALCOMM build                   : f161b04, I0380b38922
    Build Date                       : 04/06/19
    OpenGL ES Shader Compiler Version: EV031.25.03.03
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    Build Config                     : S L 6.0.7 AArch64
I/Adreno: PFP: 0x005ff110, ME: 0x005ff066
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
I/mPrinterManager: ------- position -------0
I/mPrinterManager: ------- mBarcodeTypeValue -------3
D/PrinterManagerActivity: ---------set PrinterSpeed = 1
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.printersample, PID: 8186
    java.lang.RuntimeException: stub
        at android.device.PrinterManager.open(PrinterManager.java:79)
        at com.example.printersample.PrinterManagerActivity.getPrinterManager(PrinterManagerActivity.java:308)
        at com.example.printersample.PrinterManagerActivity.access$200(PrinterManagerActivity.java:36)
        at com.example.printersample.PrinterManagerActivity$2.onClick(PrinterManagerActivity.java:148)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25896)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6747)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by xiaoqiaotq** [comment]
demo报错了 使用姿势不对吗？

**Comment by lucianomartinez27** [comment]
The same is happend to me. Could you solve it?
